<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegisterData_PostalCode</name>
   <tag></tag>
   <elementGuidId>9b7fa3a9-2ab7-48f5-b7ee-927dce1a3703</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#postcode</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='postcode']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>ecbda1eb-5e4c-43aa-b69d-6ca28d74d74d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>1d19cb4b-7aaf-46cf-9ba1-d953b409159c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control uniform-input text focus</value>
      <webElementGuid>afb21fcb-5de1-4439-ac83-a1a0347cdbd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>54f87756-3ba8-497f-868e-a64d7d0bff5f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>postcode</value>
      <webElementGuid>e3d53a91-490f-4f9c-b02e-558e4043a9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>$('#postcode').val($('#postcode').val().toUpperCase());</value>
      <webElementGuid>e4b7fcc7-e0cc-4e17-a04e-d1939581a98b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;postcode&quot;)</value>
      <webElementGuid>0a51638e-932e-4be6-baab-9b9612725615</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='postcode']</value>
      <webElementGuid>757709f5-9775-4d8a-b523-1e77ac6b1807</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account-creation_form']/div[2]/p[8]/input</value>
      <webElementGuid>1ddd8ffc-78a4-427c-b61a-8a6b3bbae938</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p[8]/input</value>
      <webElementGuid>5d6ffa8f-88d5-434c-bde5-79b1a2873d26</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'postcode' and @id = 'postcode']</value>
      <webElementGuid>f317ac80-988d-4033-b510-6e5cd60c3c5d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
