<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegisterData_FirstName</name>
   <tag></tag>
   <elementGuidId>237aea38-ccb0-4366-910a-f8219539a632</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#customer_firstname</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='customer_firstname']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dadc0186-b449-4189-8000-3584844c3a35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>$('#firstname').val(this.value);</value>
      <webElementGuid>f25e5254-ac54-4859-95bd-e6acd5024c00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d62b5d49-a696-42cf-9659-88fdb55814f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is_required validate form-control</value>
      <webElementGuid>985b2eeb-f27b-4466-9005-3e6b55df90e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>isName</value>
      <webElementGuid>4d7282bf-ed59-4491-8638-f10b900a42bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customer_firstname</value>
      <webElementGuid>6ea1dbf1-6e86-4246-bc8f-2216fc0a5aa7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>customer_firstname</value>
      <webElementGuid>73f43fb1-e237-47f8-bdfc-2bfc52f0d02c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customer_firstname&quot;)</value>
      <webElementGuid>6a592450-b567-4f5e-aff8-6b4e44098906</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customer_firstname']</value>
      <webElementGuid>2f71e9e5-b006-4816-acee-90f51227e583</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account-creation_form']/div/div[2]/input</value>
      <webElementGuid>c7623fce-a37f-473a-9eb7-2a0991d21923</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>6260d577-b64a-4866-8715-8fc2455ef0ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'customer_firstname' and @name = 'customer_firstname']</value>
      <webElementGuid>5d7b5791-32dd-4c7e-9487-42d6b5177c11</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
