<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>RegisterData_Gender</name>
   <tag></tag>
   <elementGuidId>27dbe126-defb-4eae-8fa5-ae139072be2c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>label.top</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='account-creation_form']/div/div/div/label</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>dcaf3da6-7432-4e0b-a864-39dc87852b35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>id_gender1</value>
      <webElementGuid>fe5e8e7a-b5bf-40e7-9ac5-fb15403a29e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top</value>
      <webElementGuid>0daa8541-04d3-417f-ae24-8ad065dd8b3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
							
						Mr.
						</value>
      <webElementGuid>838987e4-1c4a-451d-92dd-bf82f8ab9e34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;account-creation_form&quot;)/div[@class=&quot;account_creation&quot;]/div[@class=&quot;clearfix&quot;]/div[@class=&quot;radio-inline&quot;]/label[@class=&quot;top&quot;]</value>
      <webElementGuid>1640bc1e-f839-457b-bfbe-052dd739073c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='account-creation_form']/div/div/div/label</value>
      <webElementGuid>8f31d3df-1465-4494-9989-c65b73319e97</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Title'])[1]/following::label[1]</value>
      <webElementGuid>e3af9ff1-e640-4014-9052-2f08a891a0d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your personal information'])[1]/following::label[2]</value>
      <webElementGuid>283dfb66-3296-4e10-8dd8-9727108abc5c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Mr.']/parent::*</value>
      <webElementGuid>e1fdcba3-f748-42ab-b0ef-c67bdf334286</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div/div/label</value>
      <webElementGuid>f8d52585-6cdb-41b1-9924-226af315a15b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[(text() = '
							
						Mr.
						' or . = '
							
						Mr.
						')]</value>
      <webElementGuid>da866976-40bf-4cdc-9bc7-8a694c9d7599</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
