<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>SignIn_Password_Field</name>
   <tag></tag>
   <elementGuidId>21037636-6e04-487d-b352-8b418a5991be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#passwd</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='passwd']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>718e8bcf-7ced-4f32-a19c-5b0a67bb9865</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>is_required validate account_input form-control</value>
      <webElementGuid>71f2c421-aa50-4101-8094-424f0a18c44d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d2ba1bd7-8428-4039-8dfd-0eb8a3702166</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>isPasswd</value>
      <webElementGuid>db91d523-0746-4d99-992f-2a4767a4f527</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>passwd</value>
      <webElementGuid>34882d5d-31a6-4b8a-8c77-1e6ecc080ca3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>passwd</value>
      <webElementGuid>aa7bea3a-4a51-4bcc-8f23-b87dfbb45442</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;passwd&quot;)</value>
      <webElementGuid>d78b30d4-1b3d-4133-a086-889115bafa2e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='passwd']</value>
      <webElementGuid>b9a9101e-968c-468d-9806-6a762ea609d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login_form']/div/div[2]/span/input</value>
      <webElementGuid>afe7851f-480a-452a-a771-95075a4f2b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/input</value>
      <webElementGuid>55859781-8f55-40db-aee0-cda9af60effe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'passwd' and @name = 'passwd']</value>
      <webElementGuid>a0808f8a-7074-45aa-a2ec-ee2d284e161c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
